# Khithlainhtet - Fast YouTube Stream URL Extractor (No Download)
# Optimized for low CPU & disk usage, 2-3 seconds startup time

import os
import re
import yt_dlp
import asyncio
from pathlib import Path
from datetime import datetime, timedelta

from youtubesearchpython.future import Playlist, VideosSearch

from Newmusic import logger, config
from Newmusic.helpers import Track, utils

# --- COOKIE DATA START ---
COOKIE_DATA = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor

.youtube.com	TRUE	/	TRUE	1788834227	VISITOR_PRIVACY_METADATA	CgJNTRIEGgAgZg%3D%3D
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-3PSID	g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXounGOWJraQeCKpqG-oSwq9wACgYKAZkSARISFQHGX2MizRsEjWIBfOf8FT3Y3LMa_RoVAUF8yKpOPp3cWUdYQ5Ao5O96IuJM0076
.youtube.com	TRUE	/	TRUE	1773283987	GPS	1
.youtube.com	TRUE	/	FALSE	1804818233	SIDCC	AKEyXzW1sqaKu6ScKuu9DKvRXkDOUkGb35L6HhIlYENKXlnQKqsd44MpPeDXCEVNXNiXMxq4
.youtube.com	TRUE	/	TRUE	1773368661	YSC	V5xhbUOi2aM
.youtube.com	TRUE	/	FALSE	1807842226	SID	g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXoYEH2e75zTffKW0Xjy7JjNAACgYKAYYSARISFQHGX2Miw6hqbohoy53Wf7whYiki9xoVAUF8yKqy6CRK8cS9icqdLlHz7eND0076
.youtube.com	TRUE	/	TRUE	1804818226	__Secure-1PSIDTS	sidts-CjUBBj1CYnb_2un-x8U3DosdFcqPYVJhbg8Bk68ZCnIivIxZ-HGzJjNZhZ3mKsTTKPb9rfqcrxAA
.youtube.com	TRUE	/	TRUE	1773282831	CONSISTENCY	AG2Tqf8zG-huG-xjZAla2JPHKiMEKIrXDCYwlOHHGuhn4BqYzEQeeWHU4KBqrAnF4gXzuExsDwlRUzVRXKDOoYbqs5Cc2zhXioJl1PDof9f5T3qYUl27a9fnzomuUSXtDrxnp1hPZjCN1LI5o2cd_BCb
.youtube.com	TRUE	/	TRUE	1807842226	SAPISID	ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com	TRUE	/	TRUE	1804818233	__Secure-1PSIDCC	AKEyXzWE3s3Z4jjWsZL2ADVxRV8QrrovXNLf3fLjfD9yjEGzPH3nS1nBe6mDRNa_Z19OZUfKZw
.youtube.com	TRUE	/	TRUE	1807842226	SSID	AT0hp-hXDaolbHwv7
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-1PAPISID	ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-1PSID	g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXo1xo64CJRyhnVfADBa2PqOgACgYKAV0SARISFQHGX2Mi1ad7QdhlGEysEgNracH2bhoVAUF8yKreHDECH5KvXV8UNvE31fIb0076
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-3PAPISID	ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com	TRUE	/	TRUE	1804818233	__Secure-3PSIDCC	AKEyXzUDsCV5ZzeaZ8_RRuemevoTvbJutsmPMlGkA6CmKMPY1zz4f5-mKS5HuYiYODFDpNNRRg
.youtube.com	TRUE	/	TRUE	1804818226	__Secure-3PSIDTS	sidts-CjUBBj1CYnb_2un-x8U3DosdFcqPYVJhbg8Bk68ZCnIivIxZ-HGzJjNZhZ3mKsTTKPb9rfqcrxAA
.youtube.com	TRUE	/	FALSE	1807842226	APISID	r2h8dJdwnPtOnB6w/A696rI3lpsRhDG7gE
.youtube.com	TRUE	/	FALSE	1807842226	HSID	AKFaV2VhVw1F0A1Ki
.youtube.com	TRUE	/	TRUE	1807842227	LOGIN_INFO	AFmmF2swRAIgcB7wcOs4WNVu-ntf7mqpZ0eDodNht4tOYj9GjX_22kcCIDZ6go5sU7AJYiXaiXvDo7RTNDux2DRqDwi5aMYf_6dA:QUQ3MjNmd2RNVmZwS2M4ajJCX0NDQTZRLUhZUERGOVU3ekR3UWpkZVZ3QXVwZ1JEWmM5cDExQWV4MzRzaXF5bS1uY0dFTUlDcDJySkVkd3pZbFRVc29uSEtKT0tscDRDOG93c3Zxd0R1ZkZCTlBYcGdqaFVzMWhhOTZaRWlwTDF6WDJWU0tiM3FmRW05dUlkMlVndFROblhyejBxeGc2a09R
.youtube.com	TRUE	/	TRUE	1807842230	PREF	tz=Asia.Rangoon&f7=100&f4=4000000
.youtube.com	TRUE	/	TRUE	1788834227	VISITOR_INFO1_LIVE	rQRaTxG5Dg8
"""
# --- COOKIE DATA END ---

class YouTube:
    def __init__(self):
        self.base = "https://www.youtube.com/watch?v="
        self.cookie_dir = "Newmusic/cookies"
        self.cookie_file = None
        self.url_cache = {}       # {cache_key: (url, expiry_time)}
        self.cache_ttl = 3600     # 1 hour cache
        
        if not os.path.exists(self.cookie_dir):
            os.makedirs(self.cookie_dir)
        
        self.cookie_file = f"{self.cookie_dir}/youtube_cookies.txt"
        with open(self.cookie_file, "w", encoding="utf-8") as f:
            f.write(COOKIE_DATA)
        
        # Regex for valid & invalid URLs
        self.regex = re.compile(
            r"(https?://)?(www\.|m\.|music\.)?"
            r"(youtube\.com/(watch\?v=|shorts/|playlist\?list=)|youtu\.be/)"
            r"([A-Za-z0-9_-]{11}|PL[A-Za-z0-9_-]+)([&?][^\s]*)?"
        )
        self.iregex = re.compile(
            r"https?://(?:www\.|m\.|music\.)?(?:youtube\.com|youtu\.be)"
            r"(?!/(watch\?v=[A-Za-z0-9_-]{11}|shorts/[A-Za-z0-9_-]{11}"
            r"|playlist\?list=PL[A-Za-z0-9_-]+|[A-Za-z0-9_-]{11}))\S*"
        )
        
        logger.info("⚡ [Khithlainhtet] Stream URL Mode Active (No download)")

    def get_cookies(self):
        if self.cookie_file and os.path.exists(self.cookie_file):
            return self.cookie_file
        return None

    async def save_cookies(self, urls: list[str]) -> None:
        pass

    def valid(self, url: str) -> bool:
        return bool(re.match(self.regex, url))

    def invalid(self, url: str) -> bool:
        return bool(re.match(self.iregex, url))

    # ---------------- SEARCH & PLAYLIST ----------------
    async def search(self, query: str, m_id: int, video: bool = False) -> Track | None:
        try:
            _search = VideosSearch(query, limit=1)
            results = await _search.next()
        except Exception:
            return None
        if results and results.get("result"):
            data = results["result"][0]
            return Track(
                id=data.get("id"),
                channel_name=data.get("channel", {}).get("name"),
                duration=data.get("duration"),
                duration_sec=utils.to_seconds(data.get("duration")),
                message_id=m_id,
                title=(data.get("title") or "")[:25],
                thumbnail=(data.get("thumbnails", [{}])[-1].get("url") or "").split("?")[0],
                url=data.get("link"),
                view_count=data.get("viewCount", {}).get("short"),
                video=video,
            )
        return None

    async def playlist(self, limit: int, user: str, url: str, video: bool) -> list[Track | None]:
        tracks = []
        try:
            plist = await Playlist.get(url)
            videos = plist.get("videos", []) or []

            while len(videos) < limit and plist.get("hasMoreVideos"):
                plist = await Playlist.getNextVideos(plist)
                if not plist:
                    break
                videos.extend(plist.get("videos", []) or [])

            for data in videos[:limit]:
                thumbs = data.get("thumbnails") or [{}]
                link = data.get("link") or f"{self.base}{data.get('id')}"
                track = Track(
                    id=data.get("id"),
                    channel_name=data.get("channel", {}).get("name", ""),
                    duration=data.get("duration"),
                    duration_sec=utils.to_seconds(data.get("duration")),
                    title=(data.get("title") or "")[:25],
                    thumbnail=(thumbs[-1].get("url") or "").split("?")[0],
                    url=link.split("&list=")[0],
                    user=user,
                    view_count="",
                    video=video,
                )
                tracks.append(track)
        except Exception:
            pass
        return tracks

    # ------------------- DIRECT STREAM URL (NO DOWNLOAD) -------------------
    async def get_stream_url(self, video_id: str, video: bool = False) -> str | None:
        """
        Extract direct streaming URL without downloading.
        - video=False → audio only (fast, low bandwidth)
        - video=True → video+audio (up to 720p mp4)
        """
        url = self.base + video_id
        cookie = self.get_cookies()

        # Simplified format selection for single URL (combined audio+video or pure audio)
        if video:
            # Video: best mp4 up to 720p (includes audio)
            fmt = "best[height<=720][ext=mp4]/best[ext=mp4]/best"
        else:
            # Audio: best opus/m4a
            fmt = "bestaudio[ext=webm][acodec=opus]/bestaudio[ext=m4a]/bestaudio"

        ydl_opts = {
            "quiet": True,
            "noplaylist": True,
            "geo_bypass": True,
            "no_warnings": True,
            "cookiefile": cookie,
            "format": fmt,
        }

        def _extract():
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(url, download=False)
                # Direct stream URL from the selected format
                return info['url']

        try:
            stream_url = await asyncio.to_thread(_extract)
            if stream_url:
                return stream_url
        except Exception as e:
            logger.error(f"Stream URL extraction failed for {video_id}: {e}")
            # Fallback: best format overall
            try:
                ydl_opts_fallback = {
                    "quiet": True,
                    "noplaylist": True,
                    "cookiefile": cookie,
                    "format": "best",
                }
                def _fallback():
                    with yt_dlp.YoutubeDL(ydl_opts_fallback) as ydl:
                        info = ydl.extract_info(url, download=False)
                        return info['url']
                stream_url = await asyncio.to_thread(_fallback)
                return stream_url
            except Exception as e2:
                logger.error(f"Fallback also failed: {e2}")
                return None

    # ------------------- CACHED VERSION -------------------
    async def get_stream_url_cached(self, video_id: str, video: bool = False) -> str | None:
        """Cached version to avoid repeated extraction (TTL 1 hour)"""
        now = datetime.now()
        key = f"{video_id}_{video}"
        if key in self.url_cache:
            url, expires = self.url_cache[key]
            if now < expires:
                return url
        url = await self.get_stream_url(video_id, video)
        if url:
            self.url_cache[key] = (url, now + timedelta(seconds=self.cache_ttl))
        return url

    # ------------------- DOWNLOAD METHOD (FOR COMPATIBILITY) -------------------
    async def download(self, video_id: str, video: bool = False) -> str | None:
        """
        Compatibility method for existing code.
        Returns a direct stream URL instead of downloading a file.
        """
        return await self.get_stream_url_cached(video_id, video)
