# Khithlainhtet - Fast NexGenBots API-First YouTube Download & Search Handler

import os
import re
import yt_dlp
import random
import asyncio
import aiohttp
from pathlib import Path
from urllib.parse import urlparse

from youtubesearchpython.future import Playlist, VideosSearch

from Newmusic import logger, config
from Newmusic.helpers import Track, utils

# --- COOKIE DATA START ---
COOKIE_DATA = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor

.youtube.com	TRUE	/	TRUE	1788834227	VISITOR_PRIVACY_METADATA	CgJNTRIEGgAgZg%3D%3D
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-3PSID	g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXounGOWJraQeCKpqG-oSwq9wACgYKAZkSARISFQHGX2MizRsEjWIBfOf8FT3Y3LMa_RoVAUF8yKpOPp3cWUdYQ5Ao5O96IuJM0076
.youtube.com	TRUE	/	TRUE	1773283987	GPS	1
.youtube.com	TRUE	/	FALSE	1804818233	SIDCC	AKEyXzW1sqaKu6ScKuu9DKvRXkDOUkGb35L6HhIlYENKXlnQKqsd44MpPeDXCEVNXNiXMxq4
.youtube.com	TRUE	/	TRUE	1773368661	YSC	V5xhbUOi2aM
.youtube.com	TRUE	/	FALSE	1807842226	SID	g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXoYEH2e75zTffKW0Xjy7JjNAACgYKAYYSARISFQHGX2Miw6hqbohoy53Wf7whYiki9xoVAUF8yKqy6CRK8cS9icqdLlHz7eND0076
.youtube.com	TRUE	/	TRUE	1804818226	__Secure-1PSIDTS	sidts-CjUBBj1CYnb_2un-x8U3DosdFcqPYVJhbg8Bk68ZCnIivIxZ-HGzJjNZhZ3mKsTTKPb9rfqcrxAA
.youtube.com	TRUE	/	TRUE	1773282831	CONSISTENCY	AG2Tqf8zG-huG-xjZAla2JPHKiMEKIrXDCYwlOHHGuhn4BqYzEQeeWHU4KBqrAnF4gXzuExsDwlRUzVRXKDOoYbqs5Cc2zhXioJl1PDof9f5T3qYUl27a9fnzomuUSXtDrxnp1hPZjCN1LI5o2cd_BCb
.youtube.com	TRUE	/	TRUE	1807842226	SAPISID	ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com	TRUE	/	TRUE	1804818233	__Secure-1PSIDCC	AKEyXzWE3s3Z4jjWsZL2ADVxRV8QrrovXNLf3fLjfD9yjEGzPH3nS1nBe6mDRNa_Z19OZUfKZw
.youtube.com	TRUE	/	TRUE	1807842226	SSID	AT0hp-hXDaolbHwv7
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-1PAPISID	ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-1PSID	g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXo1xo64CJRyhnVfADBa2PqOgACgYKAV0SARISFQHGX2Mi1ad7QdhlGEysEgNracH2bhoVAUF8yKreHDECH5KvXV8UNvE31fIb0076
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-3PAPISID	ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com	TRUE	/	TRUE	1804818233	__Secure-3PSIDCC	AKEyXzUDsCV5ZzeaZ8_RRuemevoTvbJutsmPMlGkA6CmKMPY1zz4f5-mKS5HuYiYODFDpNNRRg
.youtube.com	TRUE	/	TRUE	1804818226	__Secure-3PSIDTS	sidts-CjUBBj1CYnb_2un-x8U3DosdFcqPYVJhbg8Bk68ZCnIivIxZ-HGzJjNZhZ3mKsTTKPb9rfqcrxAA
.youtube.com	TRUE	/	FALSE	1807842226	APISID	r2h8dJdwnPtOnB6w/A696rI3lpsRhDG7gE
.youtube.com	TRUE	/	FALSE	1807842226	HSID	AKFaV2VhVw1F0A1Ki
.youtube.com	TRUE	/	TRUE	1807842227	LOGIN_INFO	AFmmF2swRAIgcB7wcOs4WNVu-ntf7mqpZ0eDodNht4tOYj9GjX_22kcCIDZ6go5sU7AJYiXaiXvDo7RTNDux2DRqDwi5aMYf_6dA:QUQ3MjNmd2RNVmZwS2M4ajJCX0NDQTZRLUhZUERGOVU3ekR3UWpkZVZ3QXVwZ1JEWmM5cDExQWV4MzRzaXF5bS1uY0dFTUlDcDJySkVkd3pZbFRVc29uSEtKT0tscDRDOG93c3Zxd0R1ZkZCTlBYcGdqaFVzMWhhOTZaRWlwTDF6WDJWU0tiM3FmRW05dUlkMlVndFROblhyejBxeGc2a09R
.youtube.com	TRUE	/	TRUE	1807842230	PREF	tz=Asia.Rangoon&f7=100&f4=4000000
.youtube.com	TRUE	/	TRUE	1788834227	VISITOR_INFO1_LIVE	rQRaTxG5Dg8
"""
# --- COOKIE DATA END ---

class YouTube:
    def __init__(self):
        self.base = "https://www.youtube.com/watch?v="
        self.cookies = []
        self.checked = False
        self.cookie_dir = "Newmusic/cookies"
        self.warned = False
        
        # --- NexGenBots API တိုက်ရိုက်သတ်မှတ်ချက်များ ---
        self.api_url = "https://console.nexgenbots.xyz"
        self.api_key = "30DxNexGenBots4688e6"  # Thaw Zin ၏ API Key အမှန်
        self.api_timeout = 30  
        self.api_retries = 2
        # -------------------------------------------
        
        if not os.path.exists(self.cookie_dir):
            os.makedirs(self.cookie_dir)
        
        self.cookie_file = f"{self.cookie_dir}/youtube_cookies.txt"
        with open(self.cookie_file, "w", encoding="utf-8") as f:
            f.write(COOKIE_DATA)
            
        self.regex = re.compile(
            r"(https?://)?(www\.|m\.|music\.)?"
            r"(youtube\.com/(watch\?v=|shorts/|playlist\?list=)|youtu\.be/)"
            r"([A-Za-z0-9_-]{11}|PL[A-Za-z0-9_-]+)([&?][^\s]*)?"
        )
        self.iregex = re.compile(
            r"https?://(?:www\.|m\.|music\.)?(?:youtube\.com|youtu\.be)"
            r"(?!/(watch\?v=[A-Za-z0-9_-]{11}|shorts/[A-Za-z0-9_-]{11}"
            r"|playlist\?list=PL[A-Za-z0-9_-]+|[A-Za-z0-9_-]{11}))\S*"
        )
        logger.info(f"⚡ [Khithlainhtet] NexGenBots API-First Active: {self.api_url}")

    def get_cookies(self):
        if os.path.exists(self.cookie_file):
            return self.cookie_file
        return None

    async def save_cookies(self, urls: list[str]) -> None:
        pass

    def valid(self, url: str) -> bool:
        return bool(re.match(self.regex, url))

    def invalid(self, url: str) -> bool:
        return bool(re.match(self.iregex, url))

    async def search(self, query: str, m_id: int, video: bool = False) -> Track | None:
        try:
            _search = VideosSearch(query, limit=1)
            results = await _search.next()
        except Exception:
            return None
        if results and results.get("result"):
            data = results["result"][0]
            return Track(
                id=data.get("id"),
                channel_name=data.get("channel", {}).get("name"),
                duration=data.get("duration"),
                duration_sec=utils.to_seconds(data.get("duration")),
                message_id=m_id,
                title=(data.get("title") or "")[:25],
                thumbnail=(data.get("thumbnails", [{}])[-1].get("url") or "").split("?")[0],
                url=data.get("link"),
                view_count=data.get("viewCount", {}).get("short"),
                video=video,
            )
        return None

    async def playlist(self, limit: int, user: str, url: str, video: bool) -> list[Track | None]:
        tracks = []
        try:
            plist = await Playlist.get(url)
            videos = plist.get("videos", []) or []

            while len(videos) < limit and plist.get("hasMoreVideos"):
                plist = await Playlist.getNextVideos(plist)
                if not plist:
                    break
                videos.extend(plist.get("videos", []) or [])

            for data in videos[:limit]:
                thumbs = data.get("thumbnails") or [{}]
                link = data.get("link") or f"{self.base}{data.get('id')}"
                track = Track(
                    id=data.get("id"),
                    channel_name=data.get("channel", {}).get("name", ""),
                    duration=data.get("duration"),
                    duration_sec=utils.to_seconds(data.get("duration")),
                    title=(data.get("title") or "")[:25],
                    thumbnail=(thumbs[-1].get("url") or "").split("?")[0],
                    url=link.split("&list=")[0],
                    user=user,
                    view_count="",
                    video=video,
                )
                tracks.append(track)
        except Exception:
            pass
        return tracks

    async def _api_download(self, video_id: str, video: bool = False) -> str | None:
        """NexGenBots API သို့ လမ်းကြောင်းမှန်ဖြင့် ချိတ်ဆက်ဒေါင်းလုဒ်ဆွဲသော စနစ်"""
        if not self.api_url:
            return None
            
        # ⭐ NexGenBots ရဲ့ API Route အမှန်များသို့ လဲလှယ်ထားခြင်း
        endpoint = f"{self.api_url}/api/vdown" if video else f"{self.api_url}/api/download"
        
        DOWNLOAD_DIR = "downloads"
        os.makedirs(DOWNLOAD_DIR, exist_ok=True)
        
        ext = ".mp4" if video else ".mp3"
        filename = f"{DOWNLOAD_DIR}/{video_id}{ext}"
        
        timeout = aiohttp.ClientTimeout(total=self.api_timeout)
        
        # NexGenBots Token သယ်ဆောင်ရန်အတွက် Headers တည်ဆောက်ခြင်း
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Accept": "application/json"
        }
        params = {
            "url": f"https://www.youtube.com/watch?v={video_id}"
        }

        for attempt in range(self.api_retries):
            try:
                logger.info(f"🚀 [NexGenBots API] Downloading {'Video' if video else 'Audio'} (Attempt {attempt+1})...")
                async with aiohttp.ClientSession(timeout=timeout) as session:
                    async with session.get(endpoint, params=params, headers=headers) as resp:
                        if resp.status != 200:
                            logger.warning(f"⚠️ API status error: {resp.status}")
                            continue
                            
                        content_type = resp.headers.get('content-type', '')
                        
                        # JSON Format ပြန်လာလျှင် Download URL ကို ထပ်ထုတ်ယူခြင်း
                        if 'application/json' in content_type:
                            data = await resp.json()
                            link = data.get("download_url") or data.get("url") or data.get("stream_url") or data.get("data", {}).get("url")
                            if not link:
                                continue
                                
                            async with session.get(link) as dl:
                                dl.raise_for_status()
                                with open(filename, "wb") as fw:
                                    async for chunk in dl.content.iter_chunked(65536):
                                        fw.write(chunk)
                        
                        # Binary Stream အဖြစ် တိုက်ရိုက်ပြန်လာလျှင် ဖိုင်ထဲတန်းရေးခြင်း
                        else:
                            with open(filename, "wb") as fw:
                                async for chunk in resp.content.iter_chunked(65536):
                                    fw.write(chunk)

                # ဖိုင်တကယ်ဆွဲပြီးကြောင်းနှင့် ဖိုင်အရွယ်အစား မှန်ကန်ကြောင်း စစ်ဆေးခြင်း
                if Path(filename).exists() and os.path.getsize(filename) > 50000:
                    return filename
                else:
                    if Path(filename).exists():
                        os.remove(filename)
            except Exception as ex:
                logger.warning(f"⚠️ NexGenBots API exception: {ex}")
                if Path(filename).exists():
                    try: os.remove(filename)
                    except Exception: pass
        return None

    async def download(self, video_id: str, video: bool = False) -> str | None:
        """Download Manager - Cache စစ်မည်၊ မရှိလျှင် NexGenBots API သုံးမည်၊ မရမှ Local ဒေါင်းမည်"""
        # 1. Local Cache ထဲမှာ ဖိုင်ရှိပြီးသားလား အရင်ရှာမည်
        for ext in ("mp3", "mp4", "webm", "m4a"):
            cached = f"downloads/{video_id}.{ext}"
            if Path(cached).exists() and os.path.getsize(cached) > 50000:
                return cached

        # 2. ⭐ [API FIRST MODE] NexGenBots API အသစ်ဖြင့် အရင်ဆုံး ကြိုးစားဒေါင်းမည်
        api_file = await self._api_download(video_id, video)
        if api_file:
            return api_file

        # 3. 🛡️ [FALLBACK] API မရမှသာ Local yt-dlp ဖြင့် ကွတ်ကီးသုံးပြီး ဒေါင်းမည်
        logger.info(f"🔄 NexGenBots API Failed. Falling back to local yt-dlp for {video_id}...")
        url = self.base + video_id
        cookie = self.get_cookies()
        
        base_opts = {
            "outtmpl": "downloads/%(id)s.%(ext)s",
            "quiet": True,
            "noplaylist": True,
            "geo_bypass": True,
            "no_warnings": True,
            "overwrites": True,
            "nocheckcertificate": True,
            "cookiefile": cookie,
        }

        if video:
            ydl_opts = {
                **base_opts,
                "format": "(bestvideo[height<=?1080][ext=mp4])+(bestaudio[ext=m4a]/bestaudio)/best[ext=mp4]/best",
                "merge_output_format": "mp4",
            }
        else:
            ydl_opts = {
                **base_opts,
                "format": "bestaudio[ext=webm][acodec=opus]/bestaudio/best",
            }

        def _download():
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                try:
                    ydl.download([url])
                except Exception as ex:
                    logger.warning("Local download failed: %s", ex)
                    return None
            
            for x in ("mp3", "mp4", "webm", "m4a"):
                file = f"downloads/{video_id}.{x}"
                if Path(file).exists() and os.path.getsize(file) > 50000:
                    return file
            return None

        return await asyncio.to_thread(_download)
